version: '3'
services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    network_mode: host
    environment:
      ACCOUNT_pi: ${ACCOUNT_PI_PWD}
      SAMBA_VOLUME_CONFIG_ext: "[EXT]; path = /shares/EXT; read only = no; browsable = yes; smb encrypt = no;"
      SAMBA_VOLUME_CONFIG_ext_share: "[ext_share]; path = /shares/EXT/shared; read only = no; browsable = yes; smb encrypt = no;"
    volumes:
      - /usb/WD_500GB:/shares/EXT
    restart: always
