version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Rome
    volumes:
      - $EXT/docker/plex/config:/config
      - $EXT/docker/plex/transcode:/transcode
      - $EXT/Media:/data
    ports:
      # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - 32400:32400     # Access to the Plex Media Server
      #- 1900:1900/udp  # Optional: access to the Plex DLNA Server
      #- 5353:5353/udp  # Optional: older Bonjour/Avahi network discovery
      - 8324:8324       # Optional: controlling Plex for Roku via Plex Companion
      - 32410:32410/udp # Optional: current GDM network discovery
      - 32412:32412/udp # Optional: current GDM network discovery
      - 32413:32413/udp # Optional: current GDM network discovery
      - 32414:32414/udp # Optional: current GDM network discovery
      - 32469:32469     # Optional: access to the Plex DLNA Server
    restart: unless-stopped
