version: "3"
services:
  mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto
      volumes:
      - "$EXT/docker/mosquitto/config:/mosquitto/config"
      - "$EXT/docker/mosquitto/log:/mosquitto/log"
      - "$EXT/docker/mosquitto/data/:/mosquitto/data"
      restart: always
      ports:
      - "1883:1883"
      - "9001:9001"
