version: "2.1"
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Rome
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $EXT/docker/home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
