version: "3"
services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    entrypoint: crond -f
    environment:
      - TZ=Europe/Rome
    volumes:
      - /usb/WD_500GB/docker/rclone/config:/root/.config/rclone
      - /usb/WD_500GB/docker/rclone/script/datausage.sh:/etc/periodic/daily/datausage
      - /usb/WD_500GB/docker/datausage/config/data:/data/datausage:ro
    restart: unless-stopped
