version: "2.1"
services:
  ngnix:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
       - $EXT/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
       - $EXT/docker/nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
       - $EXT/docker/nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    restart: unless-stopped
