version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    network_mode: host
    environment:
      - TZ=Europe/Rome
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TOKEN}
