version: '3'
services:
  hisense_ac:
    image: deiger/aircon:0.3.17
    container_name: hisense_ac
    healthcheck:
      disable: true
    environment:
      - CONFIG_DIR=/config
      - OPTIONS_FILE=/config/options.json
    network_mode: host
    volumes:
      - /usb/WD_500GB/docker/aircon/config:/config
    restart: unless-stopped
