version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024
      - MEM_STARTUP=128
    volumes:
      - /usb/WD_500GB/docker/unifi/config:/config
    ports:
      # https://github.com/linuxserver/docker-unifi-controller#parameters
      - 3478:3478/udp   # Unifi STUN port
      - 10001:10001/udp # Required for AP discovery
      - 8080:8080       # Required for device communication
      - 8443:8443       # Unifi web admin port
      #- 1900:1900/udp  # Optional: Required for 'Make controller discoverable on L2 network' option
      - 8843:8843       # Optional: Unifi guest portal HTTPS redirect port
      - 8880:8880       # Optional: Unifi guest portal HTTP redirect port
      - 6789:6789       # Optional: For mobile throughput test
      - 5514:5514/udp   # Optional: Remote syslog port
    restart: unless-stopped
