version: "2.1"
services:
  backend:
    image: ghcr.io/alberto97/datausage:latest
    container_name: datausage-be
    logging:
      driver: fluentd
      options:
        tag: docker.datausage
    environment:
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - $EXT/docker/datausage/config:/config
    ports:
      - "8020:8020"
    restart: unless-stopped

  frontend:
    image: ghcr.io/alberto97/datausage-fe:latest
    container_name: datausage-fe
    depends_on:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - "8021:80"
    restart: unless-stopped
