version: "2.1"
services:
  datausage:
    image: ghcr.io/alberto97/datausage:latest
    container_name: datausage
    logging:
      driver: fluentd
      options:
        tag: docker.datausage
    environment:
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /usb/WD_500GB/docker/datausage/config:/config
    ports:
      - "8020:8020"
    restart: unless-stopped
